### ISSUE TITLE
Links to the villages not taking you to the village websites websites

### ISSUE THREAD

**Issue by its-a-lisa** [beauwoods/hackervillages.github.io#1]
Not exactly sure why this is happening; looks like the information is in the websites are listed in the villages.yml file; but when you mouse over the links on the webpage; seem to just direct you to hackervillages.org

**Comment by its-a-lisa** [comment]
Ok, I think the problem is probably index.html the reference `<h4><a href="{{village.url}}"><i class="fas fa-globe"></i> {{village.name}}</a></h4>` but within villages.yml is   `link:        https://aerospacevillage.org`

**Comment by beauwoods** [comment]
Thanks, @its-a-lisa!
